src/main/java/org/choon/careerbee/common/enums/CustomResponseStatus.java, src/main/java/org/choon/careerbee/domain/auth/controller/AuthController.java, src/main/java/org/choon/careerbee/domain/auth/dto/response/ReissueResp.java, src/main/java/org/choon/careerbee/domain/auth/entity/Token.java, src/main/java/org/choon/careerbee/domain/auth/entity/enums/TokenStatus.java, src/main/java/org/choon/careerbee/domain/auth/service/auth/AuthService.java, src/main/java/org/choon/careerbee/domain/auth/service/auth/AuthServiceImpl.java
- 토큰 재발급 기능 구현 완료하였습니다.
- 토큰관련 기능은 Redis 도입시 코드 리팩토링이 필요합니다.
=> #5 feat: 토큰 재발급 기능 구현 완료

src/main/java/org/choon/careerbee/domain/company/controller/CompanyController.java, src/main/java/org/choon/careerbee/domain/company/dto/response/CompanySummaryInfo.java, src/main/java/org/choon/careerbee/domain/company/repository/custom/CompanyCustomRepository.java, src/main/java/org/choon/careerbee/domain/company/repository/custom/CompanyCustomRepositoryImpl.java, src/main/java/org/choon/careerbee/domain/company/service/CompanyQueryService.java, src/main/java/org/choon/careerbee/domain/company/service/CompanyQueryServiceImpl.java, src/main/java/org/choon/careerbee/filter/jwt/JwtAuthenticationFilter.java
#What
- 기업 간단 정보 조회기능 구현 완료했습니다.
=> #11 feat: 기업 간단 정보 조회기능 구현완료

src/main/java/org/choon/careerbee/common/enums/CustomResponseStatus.java, src/main/java/org/choon/careerbee/domain/company/controller/CompanyCommandController.java, src/main/java/org/choon/careerbee/domain/company/controller/CompanyQueryController.java, src/main/java/org/choon/careerbee/domain/company/entity/wish/WishCompany.java, src/main/java/org/choon/careerbee/domain/company/repository/wish/WishCompanyRepository.java, src/main/java/org/choon/careerbee/domain/company/service/CompanyCommandService.java, src/main/java/org/choon/careerbee/domain/company/service/CompanyCommandServiceImpl.java, src/main/java/org/choon/careerbee/filter/jwt/JwtAuthenticationFilter.java
=> #13 feat: 관심기업 등록 기능 구현 완료

src/main/java/org/choon/careerbee/domain/company/controller/CompanyCommandController.java, src/main/java/org/choon/careerbee/domain/company/dto/response/CheckWishCompanyResp.java, src/main/java/org/choon/careerbee/domain/company/service/CompanyQueryService.java, src/main/java/org/choon/careerbee/domain/company/service/CompanyQueryServiceImpl.java
=> #15 feat: 관심기업 여부 조회 구현 완료

src/main/java/org/choon/careerbee/domain/company/dto/response/CompanySummaryInfo.java, src/main/java/org/choon/careerbee/domain/company/repository/custom/CompanyCustomRepositoryImpl.java
Detail
- 응답데이터에 관심수를 반환해주지 않고 있던 문제를 `wishCount`를 추가하여 해결하였습니다.
=> #11 feat: `wishCount` 응답 데이터 추가

src/main/java/org/choon/careerbee/domain/company/controller/CompanyQueryController.java, src/main/java/org/choon/careerbee/domain/company/dto/response/CompanySearchResp.java, src/main/java/org/choon/careerbee/domain/company/repository/custom/CompanyCustomRepository.java, src/main/java/org/choon/careerbee/domain/company/repository/custom/CompanyCustomRepositoryImpl.java, src/main/java/org/choon/careerbee/domain/company/service/CompanyQueryService.java, src/main/java/org/choon/careerbee/domain/company/service/CompanyQueryServiceImpl.java
=> #25 feat: 기업 검색 기능 구현 완료

src/main/java/org/choon/careerbee/domain/company/dto/response/CompanyRangeSearchResp.java, src/main/java/org/choon/careerbee/domain/company/repository/custom/CompanyCustomRepositoryImpl.java
Detail
- 필터링을 위한 businessType 및 recruitingStatus 추가
=> refactor: 기업 범위 검색 응답 데이터 변경

src/main/java/org/choon/careerbee/domain/company/controller/CompanyCommandController.java
=> refactor: spring mvc와 충돌로 인한 uri 변경

src/main/java/org/choon/careerbee/domain/auth/repository/TokenRepository.java, src/main/java/org/choon/careerbee/filter/jwt/JwtAuthenticationFilter.java
Detail
- memberId와 Status만으로 비교하니 2개이상의 row가 조회되어 오류 발생하는 상황을 해결
=> fix: 로그아웃시 발생하는 로직에러 수정

src/main/java/org/choon/careerbee/common/api/SystemController.java, src/main/java/org/choon/careerbee/common/dto/ApiResponse.java, src/main/java/org/choon/careerbee/common/dto/ApiResponseEntity.java, src/main/java/org/choon/careerbee/domain/auth/controller/AuthController.java, src/main/java/org/choon/careerbee/domain/company/controller/CompanyCommandController.java, src/main/java/org/choon/careerbee/domain/company/controller/CompanyQueryController.java
Detail
싱글톤인 Enum의 message 필드가 예기치 않게 중복 사용되는 문제를 해결하기 위해 응답 구조를 변경하였습니다.
- 이는 Enum을 Non-Immutable하게 사용해 발생하는 문제였습니다.
=> refactor: 공통응답 구조 변경

.github/workflows/dev_deploy.yml, .github/workflows/prod_deploy.yml
=> 👷 Ci: CI/CD 파이프라인 - Initial

.github/workflows/dev_deploy.yml, .github/workflows/prod_deploy.yml
=> 👷 Ci: yml 수정

src/main/java/org/choon/careerbee/domain/auth/controller/AuthController.java, src/main/resources/application-dev.yml
Detail
- 쿠키의 지속시간을 setMaxAge를 이용하여 7일로 설정
- refreshToken의 만료일을 7일로 설정
- accessToken의 만료시간을 10분으로 설정
=> refactor: 쿠키의 만료시간 설정

.github/workflows/dev_deploy.yml, .github/workflows/prod_deploy.yml
=> 👷 Ci: CI/CD 성공 여부 알림 설정

.github/workflows/dev_deploy.yml, .github/workflows/prod_deploy.yml
=> 👷 Ci: Job 이름 수정

build.gradle, src/main/java/org/choon/careerbee/common/exception/CustomExceptionHandler.java, src/main/resources/application-dev.yml, src/main/resources/application-prod.yml
🧱 Infra: Run time Error 알림 시스템 구축
=> 🧱 Infra: Run time Error 알림 시스템 구축

.github/workflows/dev_deploy.yml, .github/workflows/prod_deploy.yml
=> 👷 Ci: Sentry 인증 토큰 환경변수로 추가

.github/workflows/prod_deploy.yml
=> 👷 Ci: DEV-PROD 변수 처리

.github/workflows/prod_deploy.yml
=> 👷 Ci: 복사 경로 재설정

.github/workflows/lint.yml, build.gradle, config/checkstyle/google_checks.xml, config/pmd/pmd-ruleset.xml
=> 👷 Ci: 정적 코드 분석 절차 추가

build.gradle, src/main/java/org/choon/careerbee/config/security/SecurityConfig.java, src/main/java/org/choon/careerbee/filter/jwt/JwtAuthenticationFilter.java, src/main/resources/application-dev.yml, src/main/resources/application-local.yml, src/main/resources/application-prod.yml
=> 🧱 Infra: Spring Actuator

.github/workflows/prod_deploy.yml
=> 👷 Ci: sed 문제 해결

.github/workflows/prod_deploy.yml
=> 👷 Ci: sed 다시 수정

.github/workflows/prod_deploy.yml
👷 Ci: awk로 frontend image를 수정하지 않도록 수정
=> 👷 Ci: awk로 frontend image를 수정하지 않도록 수정

.github/workflows/prod_deploy.yml
👷 Ci: awk로 frontend image를 수정하지 않도록 수정 2
=> 👷 Ci: awk로 frontend image를 수정하지 않도록 수정 2

.github/workflows/prod_deploy.yml
=> 👷 Ci: indentation

.github/workflows/prod_deploy.yml
=> 👷 Ci: escape 추가

.github/workflows/prod_deploy.yml, src/main/resources/application-prod.yml
👷 Ci: 쉘스크립트 실행으로 변경 및 ddl-auto 수정
=> 👷 Ci: 쉘스크립트 실행으로 변경 및 ddl-auto 수정
